development:
  access_key_id: AKIAJ7GCHFERAOT7ZRWA
  secret_access_key: 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
 
staging:
  access_key_id: AKIAJ7GCHFERAOT7ZRWA
  secret_access_key: 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
 
production:
  access_key_id: AKIAJ7GCHFERAOT7ZRWA
  secret_access_key: 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